apiVersion: apps/v1
kind: Deployment
metadata:
  name: apricotka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apricotka
  template:
    metadata:
     labels:
       app: apricotka
    spec:
      containers:
        - image: apricotka:01
          imagePullPolicy: Never
          name: apricotka
          env:
            - name: LINK_FOR_USD
              value: "http://${MINIKUBE_IP}/api/apricotkacash/usd?format=json"
            - name: LINK_FOR_GALLERY
              value: "http://${MINIKUBE_IP}/api/serviceg/gallery"
            - name: LINK_FOR_GALLERY-IMAGES
              value: "http://${MINIKUBE_IP}/api/serviceg/gallery-images"
            - name: LINK_FOR_APRICOTS
              value: "http://${MINIKUBE_IP}/api/servicei/apricots"
            - name: LINK_FOR_APRICOT-IMAGES
              value: "http://${MINIKUBE_IP}/api/servicei/apricot-images"
          ports:
            - containerPort: 80
