apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceg-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: serviceg                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: serviceg               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      initContainers:
        - name: run-migrations
          image: serviceg-migrations:05
          command: [ "migrate", "-path", "/migrations", "-database",  "$(POSTGRESQL_URL)", "goto", "$(VERSION)" ]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://admin:admin@postgres:5432/postgres?sslmode=disable"
            - name: VERSION
              value: "20220928190601"
      containers:
        - image: serviceg:03
          imagePullPolicy: Never
          name: serviceg
          envFrom:
            - configMapRef:
                name: serviceg-config
            - secretRef:
                name: serviceg-secret
          env:
          - name: SERVER_PORT
            value: "8080"
          - name: API
            value: "/api/serviceg"
          - name: SPRING_JPA_OPEN-IN-VIEW
            value: "false"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
          ports:
            - containerPort: 8080  # порт по якому можна звертатись до поди
